### PR TITLE
Fixed DeprecationWarning, updated deps

### PR DESCRIPTION
**Pull request by irudoy**
```(node:70907) DeprecationWarning: Tapable.plugin is deprecated. Use new API on '.hooks' instead```

### CODE REVIEW

**Comment by irudoy** [comment]
@quackes Are you going to take a look at this? After that PR, I want to suggest one improvement that will solve this issue: https://github.com/webpack/webpack/issues/8521. If you are not going to support this package, then I will fork it and will support it myself. Just say it.

**Comment by quackes** [comment]
Hey,
thanks for submitting the PR.
I will try to find time this evening.

I appeciate your effort!

Greetings :)

**Comment by quackes** [comment]
Nice Work thank you very much. I will update the test sample a little, and try a few things and publish this asap.

**Comment by irudoy** [comment]
Thank you 😄

**Pull request merged**
